In [80]:
import numpy as np
import math

#input
input= np.array([
                [1,1],
                [1,0],
                [0,1],
                [0,0]
])
#output
target=np.array([1,0,0,0])

#config
nun_input=2
num_hidden=4
num_output=1

#fungsi sigmoid
def sigmoid(x):
  return 1/(1+math.exp(x))
sig = np.vectorize(sigmoid)

#Inisialisasi bobot dan bias
#Hidden layer
w_hidden = np.random.uniform(low=-3, high =3, size=(nun_input, num_hidden))
b_hidden = np.random.uniform(low=-3, high =3, size=(num_hidden))

#output layer
w_output =np.random.uniform(low=-3, high=3, size=(num_hidden, num_output))
b_output =np.random.uniform(low=-3, high=3, size=(num_output))

print(w_hidden)
print(b_hidden)

#simpan loss dan accurasy

loss_values =[]
acc_values  = []

lr=0.1
epochs=80

for epoch in range(epochs):
    MSE=0
    new_target = np.zeros(target.shape)

    for idx, inp in enumerate(input):

      #batch
      #feedforward
      #hidden layer
      o_hidden = np.matmul(input[idx], w_hidden) + b_hidden
      o_hidden = sig(o_hidden)

     #output layer
      o_output = np.matmul(o_hidden, w_output)+ b_output
      o_output =sig(o_output)
     
     #Mencari error  
      error = target[idx] - o_output
      MSE = MSE + (error*error)
      new_target[idx] = o_output.round()   

      #Eror hidden
      eh = np.matmul(error, w_output.T)

     #backpropagation
      w_output = w_output + (lr * ((error * o_output * (1- o_output))* o_hidden[np.newaxis].T )) 
      b_output = b_output + (lr * ((error * o_output * (1- o_output)))) 
     
      
      w_hidden = w_hidden + (lr * (eh * o_hidden* (1- o_hidden)) * input[idx] [np.newaxis].T )
      b_hidden = b_hidden + (lr * (eh * o_hidden* (1- o_hidden)))
    
    MSE = MSE/4
    acc = 1 - (np.sum(np.absolute(target-new_target))/4)
  
    loss_values.append(MSE)
    acc_values.append(acc)
    print("epoch: " ,epoch," | error " ,MSE," | acc ", acc)

  



    

[[-1.1488365   1.2972741  -0.59666046  0.40417253]
 [-0.43782284 -0.86806001  2.55288713  2.49951505]]
[-2.85226396  2.36291585  1.38270632 -1.22302087]
epoch:  0  | error  [0.29222957]  | acc  0.25
epoch:  1  | error  [0.30017631]  | acc  0.25
epoch:  2  | error  [0.30871191]  | acc  0.0
epoch:  3  | error  [0.31783394]  | acc  0.25
epoch:  4  | error  [0.32752741]  | acc  0.25
epoch:  5  | error  [0.33776336]  | acc  0.25
epoch:  6  | error  [0.3484982]  | acc  0.25
epoch:  7  | error  [0.35967388]  | acc  0.25
epoch:  8  | error  [0.37121904]  | acc  0.25
epoch:  9  | error  [0.38305113]  | acc  0.25
epoch:  10  | error  [0.39507944]  | acc  0.25
epoch:  11  | error  [0.40720866]  | acc  0.25
epoch:  12  | error  [0.41934272]  | acc  0.25
epoch:  13  | error  [0.4313886]  | acc  0.25
epoch:  14  | error  [0.44325963]  | acc  0.25
epoch:  15  | error  [0.45487816]  | acc  0.25
epoch:  16  | error  [0.46617745]  | acc  0.25
epoch:  17  | error  [0.4771026]  | acc  0.25
epoch:  18  | e